#!/usr/bin/env bash


# plugins
# natural language processing
# fuzzy matching
# recommend tools


show ()
{
    case "${1}" in
        date)
            date +"%c"
            exit
            ;;
        time)
            date +"%r"
            exit
            ;;
    esac
}





while [[ ${#@} -gt 0 ]]
do
    case "${1}" in
        show)
            shift
            show "${@}"
            exit
        ;;
    esac
done

